version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    assignees:
      - redeboer
      - shenvitor
    commit-message:
      prefix: MAINT
    groups:
      actions:
        patterns:
          - "*"
    labels:
      - ðŸ”¨ Maintenance
    schedule:
      interval: monthly
